name: Generate contribution snake

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark
            web/public/github-contribution-grid-snake.svg
            web/public/github-contribution-grid-snake-dark.svg?palette=github-dark
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update github contribution snake"
          file_pattern: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake-dark.svg
            web/public/github-contribution-grid-snake.svg
            web/public/github-contribution-grid-snake-dark.svg
